version: '3.8'

services:
  node-server:
    build: .
    container_name: node-server-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
      - /var/run/docker.sock:/var/run/docker.sock 
    command: npm start  
    restart: always 
